#!/data/data/com.termux/files/usr/bin/bash
if [ ! -f /data/data/com.termux/files/usr/bin/zip ]; then
pkg install zip -y
fi
if [ ! -f /data/data/com.termux/files/usr/bin/unzip ]; then
pkg install unzip -y
fi
if [ ! -f /data/data/com.termux/files/usr/bin/xmllint ]; then
pkg install libxml2-utils -y
fi

unzip -o  ~/jdx/gem -d ~/jdx
chmod -R 700 ~/jdx/
mkdir -p /sdcard/data/BixDE

yes | cp -fr -t ~/.shortcuts/tasks/ BOY EMAIL JD SWITCH WON alamat beranda dikemas 1 2 3
yes | cp -fr -t ~/.shortcuts/ CLEAN
yes | cp -fr -t /data/data/com.termux/files/usr/bin/ aaacak aaairplane aaalamat aaba520 aaberanda aacancel1 aacancel2 aaclear aaco aade aadikemas aaemail aafilex aahome aajumlah aakacer aakode aapep190 aaposh aareboost aarose aaseday aasedgor aasun210 aasun700 aatroli aavocer letsgo done
yes | cp -fr -t /sdcard/data/BixDE/ Setting_.eg
 
if [ $(su -c cat /data/ranjau) == gembix ] || [ $(su -c cat /data/ranjau) == farhan ] || [ $(su -c cat /data/ranjau) == petra ] || [ $(su -c cat /data/ranjau) == vince ]; then
yes | cp -fr -t ~/.shortcuts/tasks/ PETRA wonX order cancel1 cancel2 DIYAN
elif [ $(su -c cat /data/ranjau) == mansur ]; then
yes | cp -fr -t ~/.shortcuts/tasks/ MAN
cd ~/.shortcuts/tasks/
rm -rf 1 2 3 BOY WON
elif [ $(su -c cat /data/ranjau) == endar ]; then
yes | cp -fr -t ~/.shortcuts/tasks/ Wonogiri Boyolali
cd ~/.shortcuts/tasks/
rm -rf 1 2 3 BOY WON
fi

echo "Updated."
